services:
  backend:
    build: ./backend
    environment:
      - API_BASE=http://backend:8000
      - FIGMA_TOKEN
      - FIGMA_FILE_ID
      - BRAND_LIST=default,acme,greenfield
    volumes:
      - ./backend:/app
      - ./packages:/app/packages
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build: ./web
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    volumes:
      - ./web:/usr/src/app
      - ./packages:/usr/src/app/packages
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: bash -lc "npm i && npm run dev"

  agent:
    build: ./ops/factori/agents/base
    environment:
      - API_BASE=http://backend:8000
    depends_on:
      - backend
